Repository melvinlau/acebook-facebuzz, pull requests merged in 2019-11, with the labels that each got.

#24 Feature/user authentication
  Gemfile
  Gemfile.lock
  app/assets/javascripts/welcome.js
  app/assets/stylesheets/welcome.scss
  app/controllers/application_controller.rb
  app/controllers/welcome_controller.rb
  app/helpers/welcome_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20191105113611_devise_create_users.rb
  db/migrate/20191105145713_add_names_to_users.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/welcome_controller_spec.rb
  spec/features/user_can_log_in_spec.rb
  spec/features/user_can_log_out_spec.rb
  spec/features/user_can_sign_up_spec.rb
  spec/helpers/welcome_helper_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/views/welcome/index.html.erb_spec.rb
  spec/web_helpers.rb
Labels: User Authentication

#25 Add posts to be ordered in reverse chronological
  app/controllers/posts_controller.rb
Labels: DEV ONLY

#34 updated devise settings for heroku
  config/environments/production.rb
Labels: DEV ONLY, bug

#36 Update Procfile
  Procfile
Labels: DEV ONLY

#38 Mockups Rev 1
  app/views/mockups/alec_avatar.png
  app/views/mockups/dashboard.html
  app/views/mockups/john_avatar.jpeg
  app/views/mockups/landingpage.html
  app/views/mockups/melvin_avatar.jpeg
  app/views/mockups/olly_avatar.jpeg
  app/views/mockups/style.css
  app/views/mockups/vijay_avatar.jpeg
Labels: DEV ONLY, enhancement

#45 Image upload functionality and images can be attached to the posts
  Gemfile
  Gemfile.lock
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/partials/_post_form.html.erb
  app/views/posts/index.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  config/storage.yml
  db/migrate/20191106153737_create_active_storage_tables.active_storage.rb
  db/schema.rb
  storage/6x/9r/6x9rq1kpcqyte05sktdlk2pm2one
  storage/c8/9s/c89s8fn3v7zwuu724et1720xwwof
Labels: Posts

#46 Add author's first and last names to the post
  app/views/posts/index.html.erb
  spec/features/user_can_create_posts_spec.rb
Labels: Posts

#48 Templates to partials
  Gemfile
  Gemfile.lock
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/mockups/dashboard.html.erb
  app/views/mockups/style-dark.css
  app/views/mockups/style-light.css
  app/views/mockups/welcome.html.erb
  app/views/partials/_flash-notice.html.erb
  app/views/partials/_footer.html.erb
  app/views/partials/_header.html.erb
  app/views/partials/_welcome_main.html.erb
  app/views/partials/_wrapper_bottom.html.erb
  app/views/partials/_wrapper_top.html.erb
  app/views/posts/index.html.erb
  config/routes.rb
  db/migrate/20191106182136_acts_as_votable_migration.rb
  db/schema.rb
Labels: UX

#50 posts can have line breaks
  app/views/posts/index.html.erb
  db/migrate/20191107103129_add_line_breaks_to_posts.rb
  db/schema.rb
  public/img/facebuzzLogo.png
  public/img/poki (1).jpeg
  public/img/poki-2.jpeg
  public/img/poki-3.jpeg
Labels: DEV ONLY, Posts

#56 User can sign up
  app/controllers/posts_controller.rb
  app/views/devise/registrations/new.html.erb
  config/initializers/devise.rb
  config/routes.rb
  spec/features/user_can_sign_up_spec.rb
Labels: CLIENT, Users

#63 Setup Rails layout
  app/assets/stylesheets/style.css
  app/views/layouts/application.html.erb
  app/views/mockups/style.css
  app/views/partials/_footer_links.html.erb
  app/views/partials/_header.html.erb
  app/views/partials/_header_links.html.erb
  app/views/posts/index.html.erb
  app/views/welcome/index.html.erb
Labels: UX

#61 User can add likes
  app/controllers/posts_controller.rb
  app/models/user.rb
  app/views/posts/index.html.erb
  config/routes.rb
  db/schema.rb
  spec/features/user_can_create_posts_spec.rb
  spec/features/user_can_edit_posts_spec.rb
  spec/features/user_can_like_posts_spec.rb
Labels: CLIENT, Posts

#67 Initial Omniauth setup and username parameter added to users
  Gemfile
  Gemfile.lock
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20191108105151_add_omniauth_to_users.rb
  db/schema.rb
Labels: DEV ONLY, Users

#68 Add migration for adding column wall_id to posts table, updated the p…
  app/controllers/posts_controller.rb
  app/models/post.rb
  db/migrate/20191108124525_add_wall_to_posts.rb
  db/migrate/20191108140755_change_wall_id_user_id_to.rb
  db/schema.rb
Labels: DEV ONLY, Users

#74 User 404 and username
  app/assets/images/404_image.png
  app/assets/images/cat-404.jpg
  app/controllers/.DS_Store
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/errors/error_404_user.html.erb
  config/routes.rb
  spec/features/user_can_visit_profile_spec.rb
  spec/helpers/web_helpers.rb
Labels: CLIENT, Users

#78 User 404 and username
  app/assets/images/404_image.png
  app/assets/images/cat-404.jpg
  app/controllers/.DS_Store
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/errors/error_404_user.html.erb
  config/routes.rb
  spec/features/user_can_visit_profile_spec.rb
  spec/helpers/web_helpers.rb
Labels: CLIENT, Users

#79 fix minor bugs when edited posts and own posts on profile
  app/controllers/posts_controller.rb
  app/controllers/users_controller.rb
Labels: bug

#88 Remove redundant automatically created tests and helpers
  spec/helpers/users_helper_spec.rb
  spec/helpers/welcome_helper_spec.rb
  spec/models/user_spec.rb
  spec/views/users/index.html.erb_spec.rb
  spec/views/users/profile.html.erb_spec.rb
  spec/views/welcome/index.html.erb_spec.rb
Labels: enhancement
